version: '3'

services:
  sales-taxes:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: sales-taxes:latest
    ports:
      - '8080:80'
    hostname: sales-taxes
    restart: on-failure
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
volumes:
  vendor:
